### ISSUE TITLE
Use resources as bower package instead of copying them to repository

### ISSUE THREAD

**Issue by samdark** [bizley/yii2-content-tools#1]
There's a bower package you can use.

**Comment by bizley** [comment]
I'm waiting for author to add bower so I can use it https://github.com/GetmeUK/ContentTools/issues/29
(unless there is a method to do this without him)

**Comment by samdark** [comment]
Make a pull request. It will speed things up. Also check https://hacktoberfest.digitalocean.com/ ;)

**Comment by bizley** [comment]
Cheers :)
