### ISSUE TITLE
bizley/contenttools 1.5.0 requires bower-asset/contenttools ^1.0 -> no matching package found.

### ISSUE THREAD

**Issue by kayw-geek** [bizley/yii2-content-tools#15]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bizley/contenttools ^1.5 -> satisfiable by bizley/contenttools[1.5.0].
    - bizley/contenttools 1.5.0 requires bower-asset/contenttools ^1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

composer.json

` "repositories": {
    "packagist": {
      "type": "composer",
      "url": "https://packagist.phpcomposer.com"
    }
  }`

**Comment by bizley** [comment]
You require either 

```
"repositories": [
    {
      "type": "composer",
      "url": "https://asset-packagist.org"
    }
  ]
```

(the same is used in [Yii](https://github.com/yiisoft/yii2-app-advanced/blob/master/composer.json)) or https://github.com/fxpio/composer-asset-plugin or anything else that helps you fetch bower assets.

**Comment by kayw-geek** [comment]
[InvalidArgumentException]
  Could not find a matching version of package bizley/contenttools. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-st
  ability (stable).

**Comment by bizley** [comment]
I've just installed it with composer.json:

```
{
  "require": {
    "bizley/contenttools": "^1.5"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://asset-packagist.org"
    }
  ]
}
```
and composer 1.10.1

**Comment by kayw-geek** [comment]
thanks
