### ISSUE TITLE
Case sensitive directory name on linux systems

### ISSUE THREAD

**Issue by romanjaworski** [bizley/yii2-content-tools#16]
`Invalid Argument – yii\base\InvalidArgumentException
The file or directory to be published does not exist: /var/www/html/vendor/bower/contenttools/build`
Directory name should be `bower/ContentTools/build`

**Comment by bizley** [comment]
This is really weird because it works for me with [asset packagist](https://asset-packagist.org/package/bower-asset/contenttools). What kind of tool are you using for fetching Bower packages?

**Comment by bizley** [comment]
If this fxp/composer-asset-plugin (like I suspect) there will be problem with name case indeed. The package is prepared for Asset Packagist currently. I need to mention it in the readme.

**Comment by bizley** [comment]
I've added instruction in readme for Bower fetching. Feel free to write here if this is not helping you with your issue.
