### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by gabriele-carbonai** [bizley/yii2-content-tools#4]
Hello I have some problems a doubts with images.

**1.  Need a div with a class**
I have an image that will be replace with other javascript in background.
if i do this, with the div before code:

``` php
<div class="background-image-holder">
   <?php \bizley\contenttools\ContentTools::begin(); ?>
      <img class="nsp" alt="image" src="/img/Ethiopia-National-Geographic.jpg">
   <?php \bizley\contenttools\ContentTools::end(); ?>
</div>
```

the image will be not appears, other way if i will replace like this, with the internal div:

``` php
<?php \bizley\contenttools\ContentTools::begin(); ?>
   <div class="background-image-holder">
      <img class="nsp" alt="image" src="/img/Ethiopia-National-Geographic.jpg">
   </div>
<?php \bizley\contenttools\ContentTools::end(); ?>
```

the image will be appear but not editable

I read in doc maybe the solution is by some options, like tag or style but i am not sure and i don't know how to use.
I try it without success

**2 The normal images**
with the normal images

``` php
<?php \bizley\contenttools\ContentTools::begin(); ?>
   <img class="nsp" alt="Pic" src="/img/men.jpg"> 
<?php \bizley\contenttools\ContentTools::end(); ?>
```

if i press edit button, that will take a different dimension, maybe the original one.. the script put in html different dimensions and  is not nice to see. 
it is possible not change the dimensions taking those of the website? 
maybe directly javascript file, but will be better if there is some solution by php

**edit:**
For this problem I found a solution by javascript.
in content-tools.js line 4059 

``` javascript
if (this._attributes['width']) {
// Changed this line from this._attributes['width'] to 100% fixed
   style += "width:100%;";
}
if (this._attributes['height']) {
   style += "height:" + this._attributes['height'] + "px;";
}
```

thanks
Gabriele

**Comment by bizley** [comment]
I need more information to answer this.

Ad. 1.  Do you need to add some class to the container created by the widget? You can use `options` parameter for that:

```
<?php \bizley\contenttools\ContentTools::begin([
    'options' => ['class' => 'background-image-holder']
]); ?>
```

Ad. 2. I'm afraid I don't understand the problem here. You can always resize the image while in editor mode by dragging the corner of the image.

**Comment by bizley** [comment]
Two weeks later still no answer so I'm closing this. Let me know if anything changed.
