### ISSUE TITLE
multi language content

### ISSUE THREAD

**Issue by masihfathi** [bizley/yii2-content-tools#5]
is it possible to create content with Yii::t in the views and edit it?
for example this:
Yii::t('app',editable content)
or add sth in editor which we can capable to add multi language content?

**Comment by bizley** [comment]
It is possible but not directly through this editor. You would have to add some features like additional fields for other languages that are displayed only when editing the text I guess. Or maybe edit the text in context of specific chosen language so it will be saved and you can then switch to another language context and edit the translated text again. Something like this but it's just an idea.
