### ISSUE TITLE
Update dependency to yiisoft/yii2-imagin

### ISSUE THREAD

**Issue by tomaszkane** [bizley/yii2-content-tools#8]
Hi,
can you update dependency to [yiisoft/yii2-imagine](https://github.com/yiisoft/yii2-imagine/blob/master/CHANGELOG.md)?
Version 2.1.x don't has many changes.

**Comment by bizley** [comment]
Will do. Thanks for pointing that.

**Comment by bizley** [comment]
Fixed in [1.2.0](https://github.com/bizley/yii2-content-tools/releases/tag/1.2.0) version.
