### ISSUE TITLE
Editable Toolbox?

### ISSUE THREAD

**Issue by tomaszkane** [bizley/yii2-content-tools#9]
Hi! How about edit/change toolbox? I want to remove some buttons.

It can be something like this: `editor.toolbox().tools({$this->toolbox});`
in `/src/ContentTools.php:307` InitEditor method?

**Comment by bizley** [comment]
Added [customJs](https://github.com/bizley/yii2-content-tools/blob/1.3.0/src/ContentTools.php#L183) in [1.3.0](https://github.com/bizley/yii2-content-tools/releases/tag/1.3.0) that allows to inject custom JS on editor init.

**Comment by tomaszkane** [comment]
Thanks, BTW this change is good?
https://github.com/bizley/yii2-content-tools/blob/master/src/ContentTools.php#L251
(start from semicolon)

**Comment by bizley** [comment]
Yes, it's just a precaution if someone adds custom JS without semicolon at the end. Double semicolons are valid.
